@startuml


Personnage o..>"m_boisson" Boisson
Boisson o..>"m_nom" Substantif
Substantif o..>"m_genre" "«enumeration» \n Genre"

enum "«enumeration» \n Genre" {
FEMININ
MASCULIN
}

class Substantif {

    - m_nom : String
    '- m_genre : Genre

    + getArticleDefini()
    + getNomAvecArticleDefini()
    + getArticleIndefini()
    + getNomAvecArticleIndefini()
    + getArticlePartitif()
    + getNomAvecArticlePartitif()
    + getNomAvecPreposition()

}

class Boisson {
    '- m_nom : Substantif

    + «create» Boisson(nom : String)
    + getNom(): String
    + getGenre(): Substantif
}
class Personnage {
    - m_nom : String
    '- m_boisson : Boisson

    + «create» Personnage(nom : String)
    + «create» Personnage(nom : String, boisson_preferee : Boisson)
    + dire(text : String)
    + sePresenter()
    + boire(boisson : Boisson)
}

@enduml